server.port=8081

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/nexustrack}
spring.datasource.username=${DATABASE_USER:nexustrack}
spring.datasource.password=${DATABASE_PASSWORD:nexustrack}

spring.jpa.hibernate.ddl-auto=update
